### ISSUE TITLE
Performance boost

### ISSUE THREAD

**Issue by sp90** [KyleAMathews/docker-nginx#11]
Just update nginx would maybe give some improvements

Maybe even use the smaller alpine nginx version they have

Ref(https://hub.docker.com/_/nginx/)

**Comment by KyleAMathews** [comment]
I'm rebuilding the image right now.

On Alpine, the current image is pretty small already 55mb but feel free to fork this repo and create a Alpine version.

**Comment by sp90** [comment]
Great 👍

**Comment by pascalandy** [comment]
@sp90 Have you tried alpine? Did not see it on your repos :-p

**Comment by camsjams** [comment]
I made an Alpine version with nginx v1.14 if anyone is interested - using on production with no issues:
https://github.com/LibrettoTeam/docker-nginx-alpine

(https://hub.docker.com/r/libretto/static-nginx-alpine)
