### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by tswast** [KyleAMathews/docker-nginx#20]
This project is missing a LICENSE file. From: https://opensource.google.com/docs/using/license/

> The [OSI](https://opensource.org/licenses) collects a set of licenses which grant the relevant rights for open source projects. They also maintain a widely-accepted document which outlines what makes a license open source.
> 
> Examples of unambiguous permissions are:
> 
> Section 2 of the Apache License, which grants an “irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute”.
> 
> The MIT license grants “the rights to use, copy, modify, merge, publish, distribute, sublicense”.
> 
> The GPL v.3 gives you “legal permission to copy, distribute and/or modify”.
> 
> It’s best practice to have an unambiguous LICENSE or COPYING file which lays out these rights.

**Comment by KyleAMathews** [comment]
Good catch! Missed adding that somehow.

Added:

https://github.com/KyleAMathews/docker-nginx/commit/2054105b9342c195a4e9b541658ef00ec4f3376e
