### ISSUE TITLE
[emerg] 1#0: "daemon" directive is duplicate in /etc/nginx/nginx.conf:21

### ISSUE THREAD

**Issue by thomasshanks** [KyleAMathews/docker-nginx#5]
When I run `/usr/bin/docker run -it kyma/docker-nginx`, I get:

    aviuser@tshanks-dcos-provisioning ~ $ /usr/bin/docker run -it kyma/docker-nginx
    2015/08/21 04:36:34 [emerg] 1#0: "daemon" directive is duplicate in /etc/nginx/nginx.conf:21
    nginx: [emerg] "daemon" directive is duplicate in /etc/nginx/nginx.conf:21

I'm running on CoreOS stable (717.3.0).

**Comment by KyleAMathews** [comment]
Oh... wonder why that didn't show up before. [It looks like](https://github.com/KyleAMathews/docker-nginx/search?utf8=%E2%9C%93&q=daemon) I've set `daemon off` both in the nginx.conf and in the Dockerfile `CMD`. I'll remove it from the Dockerfile `CMD` as Docker has to have Nginx not running as a daemon afaik so no point in making it overridable.

**Comment by KyleAMathews** [comment]
New Docker image is being built https://hub.docker.com/r/kyma/docker-nginx/builds/
