### ISSUE TITLE
How do i

### ISSUE THREAD

**Issue by frob** [KyleAMathews/docker-nginx#6]
How do configure the expected host? For example, how would I set this to expect traffic from www.example.com?

**Comment by arbourd** [comment]
The default configuration, in [default](https://github.com/KyleAMathews/docker-nginx/blob/master/default), binds `localhost`. To bind to `example.com` only, you'd have to change `localhost` to `example.com`.

To customize that configuration, you would have to override it in your app's/static site's Dockerfile.

More on NGINX's server blocks: https://www.nginx.com/resources/wiki/start/topics/examples/server_blocks/

**Comment by frob** [comment]
My question is less about setting up NGINX by editing the nginx conf, but instead about if there is any way to pass that as a parameter to docker. It would be nice if a simple container such as nginx didn't have to be customized to change only the host name.

**Comment by arbourd** [comment]
As far as I know, you need to edit the NGINX server block to do what you're asking. This container does not support that kind of manipulation, but I'm sure it's possible with an init script and env variables.

**Comment by sp90** [comment]
You wrap this in your own project Dockerfile and base it off this image

then you just copy in your modified version that matches your settings

``` dockerfile
# Guide here:
# https://github.com/KyleAMathews/docker-nginx

# Build docker file
# docker build -t prototype .

FROM kyma/docker-nginx

COPY myDefault /etc/nginx/sites-enabled/default

CMD 'nginx'
```

**Comment by KyleAMathews** [comment]
@sp90 if you're feeling up to another PR, that'd be great to add to the README :-)

**Comment by sp90** [comment]
👍
