### ISSUE TITLE
SSLv3 is insecure

### ISSUE THREAD

**Issue by arbourd** [KyleAMathews/docker-nginx#7]
For anyone actually using this container with SSL/TLS should disable SSLv3 because of POODLE.

https://github.com/KyleAMathews/docker-nginx/blob/master/nginx.conf#L128

**Comment by KyleAMathews** [comment]
Could you make a PR?

**Comment by arbourd** [comment]
Sure. I'll update the cypher suites with references for your review as well.

**Comment by viztastic** [comment]
Is this still an open issue? @KyleAMathews

**Comment by KyleAMathews** [comment]
@viztastic fixed now.
