### ISSUE TITLE
Update to latest h5bp nginx settings

### ISSUE THREAD

**Issue by sp90** [KyleAMathews/docker-nginx#9]
Maybe an update to match the latest update by h5bp

**Comment by KyleAMathews** [comment]
Sounds great! Would you like to put together a PR?

**Comment by KyleAMathews** [comment]
It'd be good to include actual expire rules https://github.com/h5bp/server-configs-nginx/blob/66d0c463e0a347563692e3df735512b3babdf959/h5bp/location/expires.conf

**Comment by sp90** [comment]
I can fix that up, give me some time i will get it together

**Comment by KyleAMathews** [comment]
💯

**Comment by sp90** [comment]
@KyleAMathews wanna put them in root or?

**Comment by KyleAMathews** [comment]
I think keeping it in a separate file and then just including it makes sense. Neater + easier to browse/maintain.

**Comment by sp90** [comment]
<img width="293" alt="screen shot 2016-05-11 at 18 21 52" src="https://cloud.githubusercontent.com/assets/3041602/15188303/468dcb34-17a5-11e6-8ec0-6a2b9bf74e4a.png">

This is the structure i went for for now

**Comment by KyleAMathews** [comment]
👍
